name: BOJ Evaluator Deployment

on:
  push:
    branches:
      - 'release'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy Python to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./*"
          target: "/home/ec2-user/python-app/"

      - name: Deploy and run Python on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/python-app
            
            [ ! -d "venv" ] && python3 -m venv venv
            source venv/bin/activate
            
            pip install --upgrade pip
            pip install -r requirements.txt
            
            CURRENT_PID=$(pgrep -f app.py | grep -v $$ || true)
            if [ -z "$CURRENT_PID" ]; then
              echo "> 현재 실행중인 app.py 프로세스가 없습니다."
            else
              echo "> 종료 중인 app.py PID: $CURRENT_PID"
              kill -15 $CURRENT_PID
              sleep 5
              if kill -0 $CURRENT_PID 2>/dev/null; then
                echo "> 강제 종료 중인 app.py PID: $CURRENT_PID"
                kill -9 $CURRENT_PID
              fi
            fi
            
            nohup python -u ./app.py ${{ secrets.CAPSOLVER_KEY }} > python-app.log 2>&1 &
